# Generated by Django 4.2.4 on 2023-08-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('usercity', models.CharField(max_length=15)),
                ('useremail', models.EmailField(max_length=254)),
                ('userphone', models.CharField(max_length=13)),
            ],
        ),
    ]
