# Generated by Django 4.2.4 on 2023-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlansModel',
            fields=[
                ('planid', models.IntegerField(primary_key=True, serialize=False)),
                ('planname', models.CharField(max_length=20)),
                ('plandetails', models.CharField(max_length=30)),
                ('planamount', models.IntegerField()),
            ],
        ),
    ]
